=== SUSE/saptune/ospackage/usr/share/saptune/schemas/1.0/saptune_solution_simulate.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "file:///usr/share/saptune/schemas/1.0/saptune_solution_simulate.schema.json",
    "title": "",
    "description": "Describes the output of 'saptune solution simulate.",
    "type": "object",
    "required": [
        "$schema",
        "publish time",
        "argv",
        "pid",
        "command",
        "exit code",
        "result",
        "messages"
    ],
    "additionalProperties": true,
    "propertyNames": {
        "enum": [
            "$schema",
            "publish time",
            "argv",
            "pid",
            "command",
            "exit code",
            "result",
            "messages",
            "Angela's pieces of wisdom"
        ]
    },
    "properties": {
        "$schema": {
            "description": "URI to the schema definition",
            "type": "string"
        },
        "publish time": {
            "description": "saptune timestamp of the time this JSON object was created.",
            "type": "string",
            "pattern": "^((?:(\\d{4}-\\d{2}-\\d{2}) (\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{3})?)))$",
            "examples": [
                "2022-02-16 10:51:41.163",
                "2022-01-28 17:26:19.661"
            ]
        },
        "argv": {
            "description": "The entire saptune command as it was called.",
            "type": "string",
            "minLength": 7,
            "examples": [
                "saptune --format=json note list",
                "saptune --format=json version",
                "saptune --format=json json status"
            ]
        },
        "pid": {
            "description": "PID of the saptune process creating this object.",
            "type": "integer",
            "minimum": 2
        },
        "command": {
            "description": "The saptune command (classifier), which was executed.",
            "type": "string",
            "enum": [
                "solution simulate"
            ]
        },
        "result": {
            "description": "The result (output) of the command.",
            "type": "object",
            "required": [
                "simulations",
                "attentions"
            ],
            "additionalProperties": false,
            "properties": {
                "simulations": {
                    "description": "List of simulations (lines of the table output of `saptune solution simulate`.",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": [
                            "parameter"
                        ],
                        "additionalProperties": true,
                        "propertyNames": {
                            "enum": [
                                "Note ID",
                                "Note version",
                                "parameter",
                                "expected value",
                                "override value",
                                "actual value",
                                "comment",
                                "amendments"
                            ]
                        },
                        "properties": {
                            "parameter": {
                                "description": "Name of the parameter.",
                                "type": "string",
                                "pattern": "^[^ ]+$",
                                "examples": [
                                    "LIMIT_@dba_hard_nofile",
                                    "kernel.shmall"
                                ]
                            },
                            "expected value": {
                                "description": "Value of a parameter.",
                                "type": "string",
                                "examples": [
                                    "18446744073709551615",
                                    "-nobarrier",
                                    "never"
                                ]
                            },
                            "override value": {
                                "description": "Value of a parameter.",
                                "type": "string",
                                "examples": [
                                    "18446744073709551615",
                                    "-nobarrier",
                                    "never"
                                ]
                            },
                            "actual value": {
                                "description": "Value of a parameter.",
                                "type": "string",
                                "examples": [
                                    "18446744073709551615",
                                    "-nobarrier",
                                    "never"
                                ]
                            },
                            "comment": {
                                "type": "string"
                            },
                            "amendments": {
                                "description": "Optional amendments (footnotes).",
                                "type": "array",
                                "items": {
                                    "description": "Amendment (footnote) consists of an id and the explaining text.",
                                    "type": "object",
                                    "required": [
                                        "index",
                                        "amendment"
                                    ],
                                    "additionalProperties": false,
                                    "properties": {
                                        "index": {
                                            "description": "Index of the amendment (footnote).",
                                            "type": "integer",
                                            "examples": [
                                                "11",
                                                "15"
                                            ]
                                        },
                                        "amendment": {
                                            "description": "Describes the meaning of the amendment (footnote).",
                                            "type": "string",
                                            "minLength": 1,
                                            "examples": [
                                                "the parameter is only used to calculate the size of tmpfs (/dev/shm)",
                                                "setting is not available on the system"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "attentions": {
                    "description": "Attentions printed for a Note.",
                    "type": "array",
                    "items": {
                        "required": [
                            "Note ID",
                            "attention"
                        ],
                        "additionalProperties": false,
                        "properties": {
                            "Note ID": {
                                "description": "The Note ID.",
                                "type": "string",
                                "pattern": "^[^ ]+$",
                                "examples": [
                                    "1656250",
                                    "SAP_BOBJ"
                                ]
                            },
                            "attention": {
                                "type": "string",
                                "minLength": 1
                            }
                        }
                    }
                }
            }
        },
        "exit code": {
            "description": "The return code the saptune command terminated with.",
            "type": "integer",
            "minimum": 0,
            "maximum": 255
        },
        "messages": {
            "description": "Contains all log messages normally printed on the screen in the order they were created.",
            "type": "array",
            "items": {
                "description": "A single message.",
                "type": "object",
                "required": [
                    "priority",
                    "message"
                ],
                "additionalProperties": false,
                "properties": {
                    "priority": {
                        "description": "Priority of the log messages as defined at https://confluence.suse.com/display/SAP/Logging+Guide.",
                        "type": "string",
                        "enum": [
                            "CRITICAL",
                            "ERROR",
                            "WARNING",
                            "NOTICE",
                            "INFO",
                            "DEBUG"
                        ]
                    },
                    "message": {
                        "description": "The log message itself.",
                        "type": "string",
                        "minLength": 1,
                        "examples": [
                            "main.go:57: saptune (3.0.2) started with 'saptune status'",
                            "system.go:235: saptune terminated with exit code '1'"
                        ]
                    }
                }
            }
        }
    }
}

=== SUSE/saptune/ospackage/usr/share/saptune/schemas/1.0/examples/saptune_solution_simulate.json
{
    "$schema": "file:///usr/share/saptune/schemas/1.0/saptune_solution_simulate.schema.json",
    "publish time": "2022-10-04 10:10:38.654",
    "argv": "saptune --format=json solution simulate HANA",
    "pid": 1902,
    "command": "solution simulate",
    "exit code": 0,
    "result": {
      "simulations": [
        {
          "parameter": "LIMIT_@dba_hard_nofile",
          "expected value": "@dba hard nofile 1048576",
          "actual value": "@dba hard nofile 1048576"
        },
        {
          "parameter": "LIMIT_@dba_soft_nofile",
          "expected value": "@dba soft nofile 1048576",
          "actual value": "@dba soft nofile 1048576"
        },
        {
          "parameter": "LIMIT_@sapsys_hard_nofile",
          "expected value": "@sapsys hard nofile 1048576",
          "actual value": "@sapsys hard nofile 1048576"
        },
        {
          "parameter": "LIMIT_@sapsys_soft_nofile",
          "expected value": "@sapsys soft nofile 1048576",
          "actual value": "@sapsys soft nofile 1048576"
        },
        {
          "parameter": "LIMIT_@sdba_hard_nofile",
          "expected value": "@sdba hard nofile 1048576",
          "actual value": "@sdba hard nofile 1048576"
        },
        {
          "parameter": "LIMIT_@sdba_soft_nofile",
          "expected value": "@sdba soft nofile 1048576",
          "actual value": "@sdba soft nofile 1048576"
        },
        {
          "parameter": "vm.max_map_count",
          "expected value": "2147483647",
          "actual value": "2147483647"
        },
        {
          "parameter": "net.core.rmem_max",
          "actual value": "212992",
          "comment": " [7]",
          "amendments": [
            {
              "index": 7,
              "amendment": " [7] parameter value is untouched by default"
            }
          ]
        },
        {
          "parameter": "net.core.somaxconn",
          "expected value": "4096",
          "actual value": "4096"
        },
        {
          "parameter": "net.core.wmem_max",
          "actual value": "212992",
          "comment": " [7]",
          "amendments": [
            {
              "index": 7,
              "amendment": " [7] parameter value is untouched by default"
            }
          ]
        },
        {
          "parameter": "net.ipv4.ip_local_port_range",
          "actual value": "32768 60999",
          "comment": " [7]",
          "amendments": [
            {
              "index": 7,
              "amendment": " [7] parameter value is untouched by default"
            }
          ]
        },
        {
          "parameter": "net.ipv4.ip_local_reserved_ports",
          "actual value": "",
          "comment": " [7]",
          "amendments": [
            {
              "index": 7,
              "amendment": " [7] parameter value is untouched by default"
            }
          ]
        },
        {
          "parameter": "net.ipv4.tcp_max_syn_backlog",
          "expected value": "8192",
          "actual value": "8192"
        },
        {
          "parameter": "net.ipv4.tcp_rmem",
          "actual value": "4096 131072 6291456",
          "comment": " [7]",
          "amendments": [
            {
              "index": 7,
              "amendment": " [7] parameter value is untouched by default"
            }
          ]
        },
        {
          "parameter": "net.ipv4.tcp_slow_start_after_idle",
          "expected value": "0",
          "actual value": "0"
        },
        {
          "parameter": "net.ipv4.tcp_syn_retries",
          "expected value": "8",
          "actual value": "8"
        },
        {
          "parameter": "net.ipv4.tcp_timestamps",
          "expected value": "1",
          "actual value": "1"
        },
        {
          "parameter": "net.ipv4.tcp_tw_reuse",
          "actual value": "2",
          "comment": " [7]",
          "amendments": [
            {
              "index": 7,
              "amendment": " [7] parameter value is untouched by default"
            }
          ]
        },
        {
          "parameter": "net.ipv4.tcp_window_scaling",
          "expected value": "1",
          "actual value": "1"
        },
        {
          "parameter": "net.ipv4.tcp_wmem",
          "actual value": "4096 16384 4194304",
          "comment": " [7]",
          "amendments": [
            {
              "index": 7,
              "amendment": " [7] parameter value is untouched by default"
            }
          ]
        },
        {
          "parameter": "kernel.shmmni",
          "expected value": "32768",
          "actual value": "32768"
        },
        {
          "parameter": "IO_SCHEDULER_sda",
          "expected value": "none",
          "actual value": "none"
        },
        {
          "parameter": "IO_SCHEDULER_sdb",
          "expected value": "none",
          "actual value": "none"
        },
        {
          "parameter": "IO_SCHEDULER_sdc",
          "expected value": "none",
          "actual value": "none"
        },
        {
          "parameter": "IO_SCHEDULER_sdd",
          "expected value": "none",
          "actual value": "none"
        },
        {
          "parameter": "rpm:psmisc",
          "expected value": "23.0-6.16.1",
          "actual value": "",
          "comment": " [3]",
          "amendments": [
            {
              "index": 3,
              "amendment": " [3] value is only checked, but NOT set"
            }
          ]
        },
        {
          "parameter": "rpm:uuidd",
          "expected value": "2.36.2-150300.4.17.1",
          "actual value": "2.36.2-150300.4.23.1",
          "comment": " [3]",
          "amendments": [
            {
              "index": 3,
              "amendment": " [3] value is only checked, but NOT set"
            }
          ]
        },
        {
          "parameter": "systemd:sysstat.service",
          "expected value": "start",
          "actual value": "start, disable"
        },
        {
          "parameter": "systemd:uuidd.socket",
          "expected value": "start",
          "actual value": "start, enable"
        },
        {
          "parameter": "vm.dirty_background_bytes",
          "expected value": "314572800",
          "actual value": "314572800"
        },
        {
          "parameter": "vm.dirty_bytes",
          "expected value": "629145600",
          "actual value": "629145600"
        },
        {
          "parameter": "xfsopt_barrier",
          "expected value": "-barrier",
          "comment": " [2]",
          "amendments": [
            {
              "index": 2,
              "amendment": " [2] setting is not available on the system"
            }
          ]
        },
        {
          "parameter": "xfsopt_nobarrier",
          "expected value": "-nobarrier",
          "comment": " [2]",
          "amendments": [
            {
              "index": 2,
              "amendment": " [2] setting is not available on the system"
            }
          ]
        },
        {
          "parameter": "KSM",
          "expected value": "0",
          "actual value": "0"
        },
        {
          "parameter": "THP",
          "expected value": "never",
          "actual value": "never"
        },
        {
          "parameter": "energy_perf_bias",
          "expected value": "all:0",
          "comment": " [1]",
          "amendments": [
            {
              "index": 1,
              "amendment": " [1] setting is not supported by the system"
            }
          ]
        },
        {
          "parameter": "force_latency",
          "expected value": "70",
          "comment": " [1]",
          "amendments": [
            {
              "index": 1,
              "amendment": " [1] setting is not supported by the system"
            }
          ]
        },
        {
          "parameter": "governor",
          "expected value": "all:performance",
          "comment": " [1]",
          "amendments": [
            {
              "index": 1,
              "amendment": " [1] setting is not supported by the system"
            }
          ]
        },
        {
          "parameter": "grub:intel_idle.max_cstate",
          "expected value": "1",
          "comment": " [2] [3] [6]",
          "amendments": [
            {
              "index": 2,
              "amendment": " [2] setting is not available on the system"
            },
            {
              "index": 3,
              "amendment": " [3] value is only checked, but NOT set"
            },
            {
              "index": 6,
              "amendment": " [6] grub settings are mostly covered by other settings. See man page saptune-note(5) for details"
            }
          ]
        },
        {
          "parameter": "grub:numa_balancing",
          "expected value": "disable",
          "comment": " [2] [3] [6]",
          "amendments": [
            {
              "index": 2,
              "amendment": " [2] setting is not available on the system"
            },
            {
              "index": 3,
              "amendment": " [3] value is only checked, but NOT set"
            },
            {
              "index": 6,
              "amendment": " [6] grub settings are mostly covered by other settings. See man page saptune-note(5) for details"
            }
          ]
        },
        {
          "parameter": "grub:processor.max_cstate",
          "expected value": "1",
          "comment": " [2] [3] [6]",
          "amendments": [
            {
              "index": 2,
              "amendment": " [2] setting is not available on the system"
            },
            {
              "index": 3,
              "amendment": " [3] value is only checked, but NOT set"
            },
            {
              "index": 6,
              "amendment": " [6] grub settings are mostly covered by other settings. See man page saptune-note(5) for details"
            }
          ]
        },
