=== SUSE/saptune/ospackage/usr/share/saptune/schemas/1.0/saptune_solution_list.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "file:///usr/share/saptune/schemas/1.0/saptune_solution_list.schema.json",
    "title": "",
    "description": "Describes the output of 'saptune solution list.",
    "type": "object",
    "required": [
        "$schema",
        "publish time",
        "argv",
        "pid",
        "command",
        "exit code",
        "result",
        "messages"
    ],
    "additionalProperties": true,
    "propertyNames": {
        "enum": [
            "$schema",
            "publish time",
            "argv",
            "pid",
            "command",
            "exit code",
            "result",
            "messages",
            "Angela's pieces of wisdom"
        ]
    },
    "properties": {
        "$schema": {
            "description": "URI to the schema definition",
            "type": "string"
        },
        "publish time": {
            "description": "saptune timestamp of the time this JSON object was created.",
            "type": "string",
            "pattern": "^((?:(\\d{4}-\\d{2}-\\d{2}) (\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{3})?)))$",
            "examples": [
                "2022-02-16 10:51:41.163",
                "2022-01-28 17:26:19.661"
            ]
        },
        "argv": {
            "description": "The entire saptune command as it was called.",
            "type": "string",
            "minLength": 7,
            "examples": [
                "saptune --format=json note list",
                "saptune --format=json version",
                "saptune --format=json json status"
            ]
        },
        "pid": {
            "description": "PID of the saptune process creating this object.",
            "type": "integer",
            "minimum": 2
        },
        "command": {
            "description": "The saptune command (classifier), which was executed.",
            "type": "string",
            "enum": [
                "solution list"
            ]
        },
        "result": {
            "description": "The result (output) of the command.",
            "type": "object",
            "required": [
                "available Solutions",
                "remember message"
            ],
            "additionalProperties": false,
            "properties": {
                "available Solutions": {
                    "description": "List of the available Solutions.",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": [
                            "Solution name",
                            "Note list",
                            "Solution enabled",
                            "Solution override exists",
                            "custom Solution",
                            "Solution deprecated"
                        ],
                        "additionalProperties": false,
                        "properties": {
                            "Solution name": {
                                "description": "Format of Solution name (simplified).",
                                "type": "string",
                                "pattern": "^[^ ]+$",
                                "examples": [
                                    "HANA",
                                    "myNetWeaver"
                                ]
                            },
                            "Note list": {
                                "description": "List of Notes belonging to the Solution.",
                                "type": "array",
                                "items": {
                                    "description": "The Note ID.",
                                    "type": "string",
                                    "pattern": "^[^ ]+$",
                                    "examples": [
                                        "1656250",
                                        "SAP_BOBJ"
                                    ]
                                }
                            },
                            "Solution enabled": {
                                "description": "States if the Solution is enabled.",
                                "type": "boolean"
                            },
                            "Solution override exists": {
                                "description": "States if an override file exists for the Solution.",
                                "type": "boolean"
                            },
                            "custom Solution": {
                                "description": "States if the Note is a custom Solution.",
                                "type": "boolean"
                            },
                            "Solution deprecated": {
                                "description": "States if the Solution is deprecated.",
                                "type": "boolean"
                            }
                        }
                    }
                },
                "remember message": {
                    "description": "The remember message.",
                    "type": "string",
                    "examples": [
                        "\nRemember: if you wish to automatically activate the solution's tuning options after a reboot, you must enable and start saptune.service by running:\n    saptune service enablestart\n"
                    ]
                }
            }
        },
        "exit code": {
            "description": "The return code the saptune command terminated with.",
            "type": "integer",
            "minimum": 0,
            "maximum": 255
        },
        "messages": {
            "description": "Contains all log messages normally printed on the screen in the order they were created.",
            "type": "array",
            "items": {
                "description": "A single message.",
                "type": "object",
                "required": [
                    "priority",
                    "message"
                ],
                "additionalProperties": false,
                "properties": {
                    "priority": {
                        "description": "Priority of the log messages as defined at https://confluence.suse.com/display/SAP/Logging+Guide.",
                        "type": "string",
                        "enum": [
                            "CRITICAL",
                            "ERROR",
                            "WARNING",
                            "NOTICE",
                            "INFO",
                            "DEBUG"
                        ]
                    },
                    "message": {
                        "description": "The log message itself.",
                        "type": "string",
                        "minLength": 1,
                        "examples": [
                            "main.go:57: saptune (3.0.2) started with 'saptune status'",
                            "system.go:235: saptune terminated with exit code '1'"
                        ]
                    }
                }
            }
        }
    }
}

=== SUSE/saptune/ospackage/usr/share/saptune/schemas/1.0/examples/saptune_solution_list.output.json
{
    "$schema": "file:///usr/share/saptune/schemas/1.0/saptune_solution_list.schema.json",
    "publish time": "2022-05-10 16:12:56.949",
    "argv": "saptune --out=json solution list",
    "pid": 2873,
    "command": "solution list",
    "exit code": 0,
    "result": {
        "available Solutions": [
            {
                "Solution name": "BOBJ",
                "Note list": [
                    "941735",
                    "1771258",
                    "2578899",
                    "SAP_BOBJ",
                    "2993054",
                    "1656250"
                ],
                "Solution enabled": false,
                "Solution override exists": false,
                "custom Solution": false,
                "Solution deprecated": false
            },
            {
                "Solution name": "HANA",
                "Note list": [
                    "941735",
                    "1771258",
                    "1980196",
                    "2578899",
                    "2684254",
                    "2382421",
                    "2534844",
                    "2993054",
                    "1656250"
                ],
                "Solution enabled": false,
                "Solution override exists": false,
                "custom Solution": false,
                "Solution deprecated": false
            },
            {
                "Solution name": "MAXDB",
                "Note list": [
                    "941735",
                    "1771258",
                    "2578899"
                ],
                "Solution enabled": true,
                "Solution override exists": false,
                "custom Solution": false,
                "Solution deprecated": false
            },
            {
                "Solution name": "NETWEAVER",
                "Note list": [
                    "941735",
                    "1771258",
                    "2578899",
                    "2993054",
                    "1656250",
                    "900929"
                ],
                "Solution enabled": false,
                "Solution override exists": false,
                "custom Solution": false,
                "Solution deprecated": false
            },
            {
                "Solution name": "NETWEAVER+HANA",
                "Note list": [
                    "941735",
                    "1771258",
                    "1980196",
                    "2578899",
                    "2684254",
                    "2382421",
                    "2534844",
                    "2993054",
                    "1656250"
                ],
                "Solution enabled": false,
                "Solution override exists": false,
                "custom Solution": false,
                "Solution deprecated": false
            },
            {
                "Solution name": "S4HANA-APP+DB",
                "Note list": [
                    "941735",
                    "1771258",
                    "1980196",
                    "2578899",
                    "2684254",
                    "2382421",
                    "2534844",
                    "2993054",
                    "1656250"
                ],
                "Solution enabled": false,
                "Solution override exists": false,
                "custom Solution": false,
                "Solution deprecated": false
            },
            {
                "Solution name": "S4HANA-APPSERVER",
                "Note list": [
                    "941735",
                    "1771258",
                    "2578899",
                    "2993054",
                    "1656250",
                    "900929"
                ],
                "Solution enabled": false,
                "Solution override exists": false,
                "custom Solution": false,
                "Solution deprecated": false
            },
            {
                "Solution name": "S4HANA-DBSERVER",
                "Note list": [
                    "941735",
                    "1771258",
                    "1980196",
                    "2578899",
                    "2684254",
                    "2382421",
                    "2534844",
                    "2993054",
                    "1656250"
                ],
                "Solution enabled": false,
                "Solution override exists": false,
                "custom Solution": false,
                "Solution deprecated": false
            },
            {
                "Solution name": "SAP-ASE",
                "Note list": [
                    "941735",
                    "1410736",
                    "1680803",
                    "1771258",
                    "2578899",
                    "2993054",
                    "1656250"
                ],
                "Solution enabled": false,
                "Solution override exists": false,
                "custom Solution": false,
                "Solution deprecated": false
            }
        ],
        "remember message": "\nRemember: if you wish to automatically activate the solution's tuning options after a reboot, you must enable and start saptune.service by running:\n    saptune service enablestart\n"
    },
    "messages": [
        {
            "priority": "NOTICE",
            "message": "actions.go:84: ATTENTION: You are running a test version of saptune which is not supported for production use\n"
        }
    ]
}
